### ISSUE TITLE
typo in Observability subtitle

### ISSUE THREAD

**Issue by mhrivnak** [open-cluster-management/rhacm-docs#3413]
### **THIS IS FOR EXTERNAL CUSTOMERS ONLY!**

Red Hatters please open issues in the [developer backlog](https://github.com/stolostron/backlog/issues/new/choose), or BugZilla if you are not an authorized user for the backlog.

**Note:** Doc team will update the current version and the two previous versions (n-2). For earlier versions, we will address only Sev 1, customer-reported bugs for releases in support.

## Locations of the suggested changes?

Links to the topics that contain the suggested updates:

* https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.4/html-single/observability/index#customizing-observability

Section:

* subtitle

## What are the suggested changes?

The word "your" appears twice in a row. "Read more to learn how to optimize your your managed..."

**Comment by swopebe** [comment]
@dockerymick  FYI


@mhrivnak thanks for the issue. Internally, can you see the backlog? If so, this is where we collect issues from Red Hatters.

https://github.com/stolostron/backlog/issues/new/choose


If not, we understand opening issues here, but this is reserved to outside and not tracked as closely because it is not used as much.

@jnpacker this is a plus 1 on making the backlog public so that others can open issues in the same place where we work.

**Comment by mhrivnak** [comment]
I can see it. It just seemed significantly more complex for a simple typo fix, so I hoped a quick issue here would suffice.

Generally I suggest keeping the process overhead as low as you reasonably can for contributors. If someone like me sees an opportunity to make a small contribution and has the motivation, it helps to give them an easy and obvious path to making that contribution.

**Comment by dockerymick** [comment]
I have been able to approve and merge @mhrivnak PR and merged my own. Refreshes usually occur on Thurs. From my perspective this issue can be closed
